env:
  global:
    - secure: "d71e+0ajWJGjNX5OjRaOCvv2lD32aVNzfpVqiivuSEBgoVO3Vg84KFeK3GiD\nyrXwxf7g0n4XS105jLZutOWUQp9sQno+COtc2m7WZLP9DDknvrhropB9Y6Au\n39I4AnbodXyjlImNKv04Qyq9OBotDNA/QRfYJPw/ILNWxqqAw2o="
    - secure: "Tl9PklwNXWesjSbsoUI3XYOQQj3OQyWophXkFRoV6jp7CyKLOjlWXTRHFYAb\nI1v+3JjSDvyDTKMX6/Fj5Y+pQuRQvJJpzO1i079im/w9hCoYkk0lQ1qK0ntV\nd8vdmNN/9clde68kwf+0P29npYaG09eER8RDG31wfFC63c46Czw="
install:
  - sudo apt-get install mono-devel mono-gmcs
script:
  - xbuild FF4Bot.sln
  - python ftpUpload.py im-to-poor-to-buy-an-domain.host22.com $FTPN $FTPP /home/travis/builds/Kolpa/FF4bot/FF4Bot/bin/Debug/FF4Bot.exe /public_html/downloads FF4bot.exe